######################################################################
# Automatically generated by qmake (2.01a) Fri May 3 20:39:14 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /ad/eng/users/j/h/jhua/Tetrix_EC535/game/. .

# Input
HEADERS += block.h game.h grid.cpp score.cpp nextblock.cpp
SOURCES += block.cpp game.cpp grid.cpp main.cpp nextblock.cpp score.cpp
