######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 18 19:21:51 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /ad/eng/users/j/h/jhua/Tetrix_EC535/game/. .

# Input
HEADERS += block.h game.h grid.cpp score.cpp
SOURCES += block.cpp game.cpp grid.cpp newMain.cpp oldMain.cpp score.cpp
