######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 27 21:13:41 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /ad/eng/users/p/h/phillipt/Tetrix_EC535/game/. .

# Input
HEADERS += block.h game.h grid.cpp score.cpp
SOURCES += block.cpp game.cpp grid.cpp newMain.cpp oldMain.cpp score.cpp
