######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 17 01:14:00 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /ad/eng/users/j/h/jhua/Tetrix_EC535/screen/. .

# Input
HEADERS += grid.cpp score.cpp
SOURCES += grid.cpp main.cpp score.cpp
