######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 16 09:05:48 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /ad/eng/users/j/h/jhua/Tetrix_EC535/screen/. .

# Input
HEADERS += grid.cpp
SOURCES += grid.cpp grid_example.cpp
